# Generated by Django 2.2.1 on 2019-12-10 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('gmail_username', models.CharField(max_length=128)),
                ('picture', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_username', models.CharField(max_length=128)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photeo.Contestant')),
            ],
        ),
    ]
