# Generated by Django 2.2.1 on 2019-12-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photeo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
