# Generated by Django 2.2.1 on 2019-12-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photeo', '0002_contestant_facebook_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='gmail_username',
        ),
    ]
