# Generated by Django 2.2.1 on 2019-12-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photeo', '0003_remove_contestant_gmail_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='picture',
        ),
    ]
