# Generated by Django 2.2.1 on 2019-12-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photeo', '0004_remove_contestant_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
