# Generated by Django 2.2.1 on 2019-12-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photeo', '0005_contestant_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
