# Generated by Django 2.2.1 on 2019-12-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photeo', '0007_auto_20191212_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='gmail_username',
        ),
        migrations.AddField(
            model_name='voter',
            name='gmail',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
