# Generated by Django 2.2.1 on 2019-12-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photeo', '0008_auto_20191212_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='gmail',
            new_name='email',
        ),
    ]
