# Generated by Django 2.2.1 on 2019-12-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photeo', '0009_auto_20191215_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
