# Generated by Django 2.2.1 on 2019-12-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photeo', '0010_voter_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='gmail_username',
            field=models.CharField(default='', max_length=128),
        ),
    ]
