# Generated by Django 2.2.1 on 2019-12-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photeo', '0011_contestant_gmail_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestant',
            old_name='facebook_url',
            new_name='social_account',
        ),
    ]
