# Generated by Django 2.2.1 on 2019-12-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photeo', '0012_auto_20191215_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='gmail_username',
        ),
        migrations.AddField(
            model_name='contestant',
            name='email',
            field=models.EmailField(default='', max_length=128),
        ),
    ]
